### ISSUE TITLE
Integration Notice/Error with Wordpress Elementor 

### ISSUE THREAD

**Issue by allorganic** [christianfuerst/woocommerce-hive-payment-method#2]
Hey Christian Happy Holidays:) 
So i just hooked up this plugin (awesome btw:) , but im gettin a big Notice/Error message .. heres a screenshot.. any help greatly appreciated:) Also is there a way to select multiple tokens to accept without selecting them all? Ok , thanks so kindly much apprec:) Will
<img width="1439" alt="Screen Shot 2020-12-10 at 8 36 59 AM" src="https://user-images.githubusercontent.com/25310009/101798183-1085b380-3ac8-11eb-9d9c-4359565cb0e6.png">
<img width="1433" alt="Screen Shot 2020-12-10 at 8 36 36 AM" src="https://user-images.githubusercontent.com/25310009/101798193-11b6e080-3ac8-11eb-8f3f-739c3a122654.png">

text version:

Notice: product_type was called
incorrectly
. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/genesis/page.php'), genesis, do_action('genesis_loop'), WP_Hook->do_action, WP_Hook->apply_filters, genesis_do_loop, genesis_standard_loop, do_action('genesis_entry_content'), WP_Hook->do_action, WP_Hook->apply_filters, genesis_do_post_content, the_content, apply_filters('the_content'), WP_Hook->apply_filters, Elementor\Frontend->apply_builder_in_content, Elementor\Frontend->get_builder_content, Elementor\Core\Base\Document->print_elements_with_wrapper, Elementor\Core\Base\Document->print_elements, Elementor\Element_Base->print_element, Elementor\Element_Base->_print_content, Elementor\Element_Base->print_element, Elementor\Element_Base->_print_content, Elementor\Element_Base->print_element, Elementor\Widget_Base->_print_content, Elementor\Widget_Base->render_content, Elementor\Controls_Stack->rende in /var/www/wp-includes/functions.php on line 5229
2214.996
HIVE
Add to cart

**Comment by christianfuerst** [comment]
It seems like these warnings doesn't come from `woocommerce-hive-payment-method`.

Instead it looks like your current theme is throwing those warnings because it calls `product_type` which is deprecated in woocommerce. 

Maybe this link will be helpful and contains the fix you are looking for:
https://wordpress.org/support/topic/product-type-called-incorrectly/

Regarding selecting multiple tokens instead of all:
Yes you can! It's a multi select control - just deselect all first, then hold STRG key and only select those tokens you desire.
